-- liquibase formatted sql

-- changeset moldo:1732737910965-1
CREATE TABLE "article" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR(255) NOT NULL, "content" TEXT, CONSTRAINT "article_pkey" PRIMARY KEY ("id"));

-- changeset moldo:1732737910965-2
CREATE TABLE "comment" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user" VARCHAR(255), "content" TEXT, "article_id" INTEGER, CONSTRAINT "comment_id" PRIMARY KEY ("id"));

-- changeset moldo:1732737910965-3
CREATE TABLE "tutorial" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR(255) NOT NULL, "description" TEXT, "publication_date" date, CONSTRAINT "tutorial_pkey" PRIMARY KEY ("id"));

-- changeset moldo:1732737910965-4
ALTER TABLE "comment" ADD CONSTRAINT "comment_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "article" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

