-- liquibase formatted sql

-- changeset moldo:1732230384308-1
CREATE TABLE "tutorial"
(
    "id"               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title"            VARCHAR(255)                             NOT NULL,
    "description"      TEXT,
    "publication_date" date,
    CONSTRAINT "tutorial_pkey" PRIMARY KEY ("id")
);

