-- liquibase formatted sql


-- changeset moldo:1732230384308-2
CREATE TABLE "article"
(
    "id"    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" VARCHAR(255)                             NOT NULL,
    "content" TEXT,
    CONSTRAINT "article_pkey" PRIMARY KEY ("id")
);

-- changeset moldo:1732230384308-3
CREATE TABLE "comment"
(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user" VARCHAR(255),
    "content" TEXT,
    "article_id" INTEGER REFERENCES "article" ("id"),
    CONSTRAINT "comment_id" PRIMARY KEY ("id")
);

