apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
        - name: app
          image: dukov82/greetings:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          imagePullPolicy: Always